### ISSUE TITLE
Deutsche Sprache schwere Sprache

### ISSUE THREAD

**Issue by R0xoy** [kbitGit/manga_volume_tracker#11]
Kein Bänder gekauft junge!
![1mbcm8](https://user-images.githubusercontent.com/72351845/148604331-75806fa6-ec3a-4fa8-b2ca-26fdb8b3ff3a.jpg)

**Comment by SM0TH** [comment]
hab ich auch schon gesehen, sollte sich das entwicklerteam mal anschauen

**Comment by kbitGit** [comment]
Fixed with Commit e2fea932b242e4482606774d8b8f4febb1241d8a
